### ISSUE TITLE
Chức năng đăng nhập bằng User hoặc Email

### ISSUE THREAD

**Issue by hoainv-relipasoft** [relipasoft/religram-react#28]
# Mô tả
## `[PM]` Mục đích của việc tạo issue `Required`
- 
![image](https://user-images.githubusercontent.com/51735507/62912101-e8d9ea80-bdb0-11e9-9c1d-18dc092a2a4f.png)

## `[PM]` Yêu cầu và mong muốn đạt được của issue 
- Require 2 trường username và password
- Không cho phép user nhấn submit liên tiếp
- khi click vào link "Create New Account" => chuyển sang màn hình tạo mới account
- Khi click vào link "Back to login" => chuyển sang màn hình login

## `[PM]` Tiêu chuẩn nghiệm thu (Mức User Acceptance Test) `Required`
- [x] Code đã selftest chưa
- [ ] Code đã được review
- [x] Đã viết UT
- [ ] Đã có AT
- [ ] Đã có testcase result chưa

## `[Developer]` Mô tả cách làm dự kiến và thời gian estimate tương ứng. Tối đa 4h cho 1 gạch đầu dòng `Required`
- Làm form
- Call API nếu có lỗi thì show lỗi 3s
- Viết UT

## `[Cả team]` Rủi ro có thể xảy ra với phương án trên. Cần mở tài liệu dự án để tham khảo cho chắc chắn `Required`
-   

# Ghi chép chi tiết khi thực hiện task `Required all`
## `[Tester]` Testcase Result 
- Link:

## `[Developer]` Danh sách các màn hình hoặc chức năng bị ảnh hưởng bởi việc sửa đổi này
-  Không có

## `[Developer]` Release notes
- Backup:
Tạo branch backup: git checkout-b master_15_08_2019
- Release:
tao nhanh code rlg_28: git branch rlg_28
Pull source code mới nhất: git pull origin master
chạy npm install để cài đặt thư viện
- Rollback:
Checkout về branch backup: git checkout master_15_08_2019
